version: '3.1'
services:
    blog-mysql:
        image: 'mysql:8.0'
        working_dir: /application
        container_name: blog-mysql
        volumes:
            - '.:/application'
            - './phpdocker/blog.sql:/docker-entrypoint-initdb.d/datadump.sql'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=blog
            - MYSQL_USER=blog
            - MYSQL_PASSWORD=123456
        ports:
            - '36001:3306'

    blog-webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '36000:80'

    blog-php-fpm:
        build: phpdocker/php-fpm
        container_name: blog-php-fpm
        working_dir: /application
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=blog
            - MYSQL_USER=blog
            - MYSQL_PASSWORD=123456
            - MYSQL_HOST=blog-mysql
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'

    blog-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: blog-phpmyadmin
        links:
          - blog-mysql
        environment:
          - MYSQL_ROOT_PASSWORD=123456
          - PMA_HOST=blog-mysql
          - PMA_PORT=3306
        ports:
          - '36002:80'
        restart: always

    composer:
        image: composer
        container_name: blog-composer
        working_dir: /application
        command: install
        volumes:
           - '.:/application'